### ISSUE TITLE
すりガラスの見た目を良くする

### ISSUE THREAD

**Issue by gedorinku** [gedorinku/frosted-glass#2]
# 方針
- 主に建築シーンで使われることを想定
- バニラテクスチャとの親和性を大事にする
- ある程度現実に即したすりガラスの見た目にする

**Comment by mucho613** [comment]
## ありそうな案
(ぼかしをシェーダー、半透明効果をテクスチャでかける前提で)

- テクスチャ
  - 白の半透明(α: 50%～80% ぐらいが自然か？実験して試す)
  - ふち取りをする(バニラのガラスのような)
    - 中央部分とのコントラストは少ないほうがいい 
  - ノイズをかける
    - 自然なノイズにしようとするとテクスチャ解像度を高める必要があるが、そこまでするならシェーダーでやった方がいい

**Comment by mucho613** [comment]
以下に分解するため close
#17
#18
